### ISSUE TITLE
Error at v 1.2.4 ?

### ISSUE THREAD

**Issue by marceloboeira** [cassiomarques/enumerate_it#45]
My CI Server (Codeship) is failing because of enumerate_it:

```terminal
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Could not find enumerate_it-1.2.4 in any of the sources
```

**Comment by cassiomarques** [comment]
https://rubygems.org/gems/enumerate_it/versions/1.2.4 shows that the version is currently available.

**Comment by cassiomarques** [comment]
Hum... I think I changed the code, released a new version but forgot to push the changes to Github. Are you trying to get it from Github instead of Rubygems?

**Comment by marceloboeira** [comment]
Nope, from Rubygems.

**Comment by cassiomarques** [comment]
Can you check if `gem install enumerate_it -v 1.2.4` works locally for you? If it does, then the CI should be able to download it as well.

**Comment by marceloboeira** [comment]
@cassiomarques it works locally, I've already checked.

**Comment by cassiomarques** [comment]
Sometimes bundle install will fail with weird messages. If it works for you locally then the 1.2.4 version is definitely available on Rubygems. Could be a DNS resolution problem on your CI problem.

**Comment by marceloboeira** [comment]
@cassiomarques Well, you can close the issue and the PR, if you feel like it, and I'll check with the guys at Codeship about Cache/DNS, but has been a while since it is like this. v1.2.3 works fine, but when I update to 1.2.4 it crashes my deploy.

**Comment by marceloboeira** [comment]
@cassiomarques I just got a green build, I reseted the dependency cache and it works fine now.

You can close the issue now, thanks!
